### ISSUE TITLE
Issue in /src/pages/get-started/index.md

### ISSUE THREAD

**Issue by meker12** [AdobeDocs/commerce-events#124]
Consider adding a link to the Commerce I/O Events Guide in the [Using Adobe I/O Events](https://developer.adobe.com/events/docs/guides/using/) topic in the main _Adobe I/O Events Guide_ . It's an index to the docs for setting up and using Adobe I/O Events with various Adobe solutions.

**Comment by jeff-matthews** [comment]
This should be reported in the [AdobeDocs/adobe-io-events](https://github.com/AdobeDocs/adobe-io-events) repo.
